export const blogs = [
  {
    id: 1,
    title: "How to Start a Successful Blog in 2025",
    slug: "start-successful-blog-2025",
    author: "Jane Doe",
    published: "2025-01-15",
    text: "Learn the essential steps to start a profitable blog this year...",
    image: "https://picsum.photos/seed/1/400/250",
  },
  {
    id: 2,
    title: "Top 10 AI Tools for Content Creators",
    slug: "top-ai-tools-content-creators",
    author: "Mark Lee",
    published: "2025-01-12",
    text: "AI can boost productivity—here are the top tools you should use...",
    image: "https://picsum.photos/seed/2/400/250",
  },
  {
    id: 3,
    title: "Mastering SEO: Beginner’s Guide",
    slug: "mastering-seo-beginners-guide",
    author: "Sarah Kim",
    published: "2025-01-10",
    text: "Everything you need to know to rank higher on Google...",
    image: "https://picsum.photos/seed/3/400/250",
  },
  {
    id: 4,
    title: "Understanding JavaScript ES2025 Features",
    slug: "javascript-es2025-new-features",
    author: "John Carter",
    published: "2025-01-09",
    text: "A walkthrough of the newest JavaScript updates...",
    image: "https://picsum.photos/seed/4/400/250",
  },
  {
    id: 5,
    title: "10 Ways to Improve Your Productivity",
    slug: "improve-productivity-10-ways",
    author: "Emily Stone",
    published: "2025-01-08",
    text: "Boost your daily output with these simple habits...",
    image: "https://picsum.photos/seed/5/400/250",
  },
  {
    id: 6,
    title: "Best Web Development Trends in 2025",
    slug: "web-development-trends-2025",
    author: "Alan Brooks",
    published: "2025-01-06",
    text: "Discover what's shaping the future of web dev...",
    image: "https://picsum.photos/seed/6/400/250",
  },
  {
    id: 7,
    title: "A Guide to Healthy Remote Work Routine",
    slug: "healthy-remote-work-routine",
    author: "Nina Patel",
    published: "2025-01-05",
    text: "Tips for staying healthy and productive while working remotely...",
    image: "https://picsum.photos/seed/7/400/250",
  },
  {
    id: 8,
    title: "Why Cybersecurity Matters in 2025",
    slug: "cybersecurity-importance-2025",
    author: "Leo Johnson",
    published: "2025-01-03",
    text: "Cyber threats are rising—here’s what you should know...",
    image: "https://picsum.photos/seed/8/400/250",
  },
  {
    id: 9,
    title: "The Future of Blockchain Beyond Crypto",
    slug: "blockchain-future-beyond-crypto",
    author: "Olivia Martins",
    published: "2025-01-02",
    text: "Blockchain is more than cryptocurrency—here’s how...",
    image: "https://picsum.photos/seed/9/400/250",
  },
  {
    id: 10,
    title: "How to Build Your Personal Brand Online",
    slug: "build-personal-brand-online",
    author: "Daniel Park",
    published: "2025-01-01",
    text: "Grow your online presence with these proven strategies...",
    image: "https://picsum.photos/seed/10/400/250",
  },
];
